name: mypushnotifications
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  firebase: ^9.0.3
  firebase_messaging: ^15.1.1
  cloud_firestore: ^5.4.1
  firebase_auth: ^5.2.1
  cloud_functions: ^5.1.1
  flutter_local_notifications: ^17.2.2
  flutter_staggered_animations: ^1.1.1
  timezone: ^0.9.4
  flutter_native_timezone: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl_utils: ^2.8.5  # Add this line

flutter:
  uses-material-design: true
  generate: true

  assets:
    - lib/l10n/

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated